from uuid import uuid4
from typing import Optional, TYPE_CHECKING
from sqlalchemy import Integer, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.core.database import Base

if TYPE_CHECKING:
    from app.models.role_permission import RolePermission


class Permission(Base):
    __tablename__ = "permissions"
    __table_args__ = {"schema": "boards"}

    # Serial integer for indexing — generated by the DB, never set by ORM
    seq_id: Mapped[int] = mapped_column(Integer, nullable=False)
    # UUID primary key
    id: Mapped[str] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid4
    )
    name: Mapped[str] = mapped_column(String(100), unique=True, nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Reverse relationship to RolePermission
    role_permissions: Mapped[list["RolePermission"]] = relationship(
        "RolePermission", back_populates="permission", lazy="select"
    )
