from uuid import uuid4
from typing import TYPE_CHECKING
from sqlalchemy import Integer, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.core.database import Base

if TYPE_CHECKING:
    from app.models.role import Role
    from app.models.permission import Permission


class RolePermission(Base):
    __tablename__ = "role_permissions"
    __table_args__ = {"schema": "boards"}

    # Serial integer for indexing — generated by the DB, never set by ORM
    seq_id: Mapped[int] = mapped_column(Integer, nullable=False)
    # UUID primary key
    id: Mapped[str] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid4
    )
    role_id: Mapped[str] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("boards.roles.id", ondelete="CASCADE"),
        nullable=False,
    )
    permission_id: Mapped[str] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("boards.permissions.id", ondelete="CASCADE"),
        nullable=False,
    )

    # Relationships
    role: Mapped["Role"] = relationship(
        "Role", back_populates="role_permissions", lazy="select"
    )
    permission: Mapped["Permission"] = relationship(
        "Permission", back_populates="role_permissions", lazy="select"
    )
